/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package factura;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author James Burris
 */
public class frmFactura extends javax.swing.JInternalFrame {
    
    float x = 0;
    float y = 0;

    /**
     * Creates new form frmFactura
     */
//    private final LinkedList lstArticulos = new LinkedList();
    public frmFactura() {
        initComponents();
        actualizarTablaArticulo();
        actualizarTablaVenta();
    }
    
    private void actualizarTablaArticulo() {
        String[] etiquetasTabla = {"Código Producto", "Nombre Producto",
            "Descripción Producto", "Precio Producto", "Cantidad"};
        Object[][] data = Formulario.Articulo.arregloArticulo();
        DefaultTableModel deftTableModel = new DefaultTableModel(data, etiquetasTabla);
        this.tablaProducto.setModel(deftTableModel);
    }
    
    private void actualizarTablaVenta() {
        String[] etiquetasTabla1 = {"Código", "Nombre",
            "Descripción", "Precio", "Cantidad", "SubTotal"};
        Object[][] data = Formulario.Articulo.arregloVenta();
        DefaultTableModel deftTableModel = new DefaultTableModel(data, etiquetasTabla1);
        this.tablaVenta.setModel(deftTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAgrgPrdct = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblCodPrdct = new javax.swing.JLabel();
        txtCodPrdct = new javax.swing.JTextField();
        lblNombPrdct = new javax.swing.JLabel();
        txtNombPrdct = new javax.swing.JTextField();
        lblDescpPrdct = new javax.swing.JLabel();
        txtDescpPrdct = new javax.swing.JTextField();
        lblCantdPrdct = new javax.swing.JLabel();
        txtCantdPrdct = new javax.swing.JTextField();
        lblPrecioPrdct = new javax.swing.JLabel();
        txtPreVntPrdct = new javax.swing.JTextField();
        btnGrdr = new javax.swing.JButton();
        btnCncl = new javax.swing.JButton();
        btnAgrg = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        pnlRlzVnt = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblNoFct = new javax.swing.JLabel();
        txtNoFct = new javax.swing.JTextField();
        lblFech = new javax.swing.JLabel();
        txtFch = new javax.swing.JTextField();
        lblRtn = new javax.swing.JLabel();
        txtRtn = new javax.swing.JTextField();
        lblNomb = new javax.swing.JLabel();
        txtNomb = new javax.swing.JTextField();
        btnEncbz = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtbuscarCodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDescpDet = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblPrVntDet = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCntdDet = new javax.swing.JTextField();
        lblNombPrdcDetll = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnIngrArt = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblFctEnc = new javax.swing.JLabel();
        lblFchEnc = new javax.swing.JLabel();
        lblRtnEnc = new javax.swing.JLabel();
        lblNombEnc = new javax.swing.JLabel();
        lblSubTtl = new javax.swing.JLabel();
        lblIsv = new javax.swing.JLabel();
        lblTtlPgr = new javax.swing.JLabel();

        setVisible(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCodPrdct.setText("Código producto:");

        lblNombPrdct.setText("Nombre producto:");

        lblDescpPrdct.setText("Descripción producto:");

        lblCantdPrdct.setText("Cantidad producto:");

        txtCantdPrdct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantdPrdctActionPerformed(evt);
            }
        });

        lblPrecioPrdct.setText("Precio venta:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescpPrdct)
                    .addComponent(lblNombPrdct, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodPrdct, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecioPrdct)
                            .addComponent(lblCantdPrdct))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodPrdct)
                    .addComponent(txtNombPrdct)
                    .addComponent(txtDescpPrdct)
                    .addComponent(txtCantdPrdct)
                    .addComponent(txtPreVntPrdct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodPrdct)
                    .addComponent(txtCodPrdct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombPrdct)
                    .addComponent(txtNombPrdct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescpPrdct)
                    .addComponent(txtDescpPrdct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantdPrdct)
                    .addComponent(txtCantdPrdct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioPrdct)
                    .addComponent(txtPreVntPrdct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnGrdr.setText("Guardar");
        btnGrdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrdrActionPerformed(evt);
            }
        });

        btnCncl.setText("Cancelar");

        btnAgrg.setText("Agregar");
        btnAgrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrgActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProducto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAgrg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGrdr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCncl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrg)
                    .addComponent(btnGrdr)
                    .addComponent(btnCncl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAgrgPrdctLayout = new javax.swing.GroupLayout(pnlAgrgPrdct);
        pnlAgrgPrdct.setLayout(pnlAgrgPrdctLayout);
        pnlAgrgPrdctLayout.setHorizontalGroup(
            pnlAgrgPrdctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgrgPrdctLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAgrgPrdctLayout.setVerticalGroup(
            pnlAgrgPrdctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgrgPrdctLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Producto", pnlAgrgPrdct);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNoFct.setText("N° Factura:");

        lblFech.setText("Fecha:");

        lblRtn.setText("RTN:");

        lblNomb.setText("Nombre:");

        btnEncbz.setText("Ingresar Encabezado");
        btnEncbz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncbzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEncbz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNoFct)
                            .addComponent(lblFech)
                            .addComponent(lblRtn)
                            .addComponent(lblNomb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoFct, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtFch)
                            .addComponent(txtRtn)
                            .addComponent(txtNomb))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEncbz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoFct)
                    .addComponent(txtNoFct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFech)
                    .addComponent(txtFch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomb)
                    .addComponent(txtNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setText("Ingresar Detalle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Código Producto:");

        jLabel11.setText("Nombre Producto:");

        jLabel13.setText("Descripción:");

        jLabel15.setText("Precio Venta:");

        jLabel17.setText("Cantidad a vender:");

        lblNombPrdcDetll.setText("jLabel1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescpDet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrVntDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCntdDet)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbuscarCodigo)
                                    .addComponent(lblNombPrdcDetll, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(lblNombPrdcDetll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblDescpDet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblPrVntDet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCntdDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaVenta);

        jLabel18.setText("SubTotal:");

        jLabel19.setText("ISV:");

        jLabel20.setText("Total a pagar:");

        btnIngrArt.setText("Ingresar Articulo");
        btnIngrArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngrArtActionPerformed(evt);
            }
        });

        jButton9.setText("Hacer venta");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("N° Factura:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Fecha:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("RTN:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Nombre:");

        lblSubTtl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTtl.setText(" ");

        lblIsv.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIsv.setText(" ");

        lblTtlPgr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTtlPgr.setText(" ");

        javax.swing.GroupLayout pnlRlzVntLayout = new javax.swing.GroupLayout(pnlRlzVnt);
        pnlRlzVnt.setLayout(pnlRlzVntLayout);
        pnlRlzVntLayout.setHorizontalGroup(
            pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRlzVntLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRlzVntLayout.createSequentialGroup()
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRlzVntLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                                .addGap(65, 65, 65))
                            .addGroup(pnlRlzVntLayout.createSequentialGroup()
                                .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNombEnc, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(lblRtnEnc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFchEnc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFctEnc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlRlzVntLayout.createSequentialGroup()
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlRlzVntLayout.createSequentialGroup()
                                .addComponent(btnIngrArt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)))
                            .addGroup(pnlRlzVntLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSubTtl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTtlPgr, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addGap(64, 64, 64))))
        );
        pnlRlzVntLayout.setVerticalGroup(
            pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRlzVntLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRlzVntLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRlzVntLayout.createSequentialGroup()
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(lblFctEnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblFchEnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(lblRtnEnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(lblNombEnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIngrArt)
                        .addComponent(jButton9))
                    .addGroup(pnlRlzVntLayout.createSequentialGroup()
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lblSubTtl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(lblIsv))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRlzVntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblTtlPgr))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Realizar Venta", pnlRlzVnt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantdPrdctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantdPrdctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantdPrdctActionPerformed

    private void btnGrdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrdrActionPerformed
        // TODO add your handling code here:
        Articulo articulo = new Articulo();
        if (this.txtCodPrdct.getText().isEmpty()
                || txtNombPrdct.getText().isEmpty()
                || txtDescpPrdct.getText().isEmpty()
                || txtPreVntPrdct.getText().isEmpty()
                || txtCantdPrdct.getText().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAgrgPrdct, "No deben haber campos vacios.");
        } else {
            articulo.setCodigoProducto(Integer.parseInt(txtCodPrdct.getText()));
            articulo.setNombreProducto(txtNombPrdct.getText());
            articulo.setDescripcionProducto(txtDescpPrdct.getText());
            articulo.setPrecioProducto(Float.parseFloat(txtPreVntPrdct.getText()));
            articulo.setCantidadProducto(Integer.parseInt(txtCantdPrdct.getText()));
            Formulario.Articulo.agregarProducto(articulo);
            actualizarTablaArticulo();
        }
    }//GEN-LAST:event_btnGrdrActionPerformed

    private void btnEncbzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncbzActionPerformed
        // TODO add your handling code here:
        lblFctEnc.setText(txtNoFct.getText());
        lblFchEnc.setText(txtFch.getText());
        lblRtnEnc.setText(txtRtn.getText());
        lblNombEnc.setText(txtNomb.getText());
    }//GEN-LAST:event_btnEncbzActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        Articulo articulo = new Articulo();

        Articulo buscArtc = Formulario.Articulo.buscar_producto_objeto(Integer.parseInt(txtbuscarCodigo.getText()));
        lblNombPrdcDetll.setText(buscArtc.getNombreProducto());
        lblDescpDet.setText(buscArtc.getDescripcionProducto());
        lblPrVntDet.setText(String.valueOf(buscArtc.getPrecioProducto()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAgrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgrgActionPerformed

    private void btnIngrArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngrArtActionPerformed
        // TODO add your handling code here:
        Articulo articulo = new Articulo();
        if (txtCntdDet.getText().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAgrgPrdct, "No deben haber campos vacios.");
        } else {
            articulo.setSubCodigoProducto(Integer.parseInt(txtbuscarCodigo.getText()));
            articulo.setSubNombreProducto(lblNombPrdcDetll.getText());
            articulo.setSubDescripcionProducto(lblDescpDet.getText());
            articulo.setSubPrecioProducto(Float.parseFloat(lblPrVntDet.getText()));
            articulo.setSubCantidadProducto(Integer.parseInt(txtCntdDet.getText()));
            articulo.setSubTotal(Float.parseFloat(lblPrVntDet.getText()));
            //float j = 58;
            float j = Float.parseFloat(lblPrVntDet.getText());
            float i = Float.parseFloat(txtCntdDet.getText());
            float p = i * j;
//float h = Float.parseFloat((Float.parseFloat(lblPrVntDet.getText())*(Integer.parseInt(txtCntdDet.getText()))));
            articulo.setSubTotal(p);
            Formulario.Articulo.agregarSubTotalProducto(articulo);
            actualizarTablaVenta();
            y = articulo.getSubTotal() + x;
            x = y;
            lblSubTtl.setText(String.valueOf(x));
            float k  = (float) (x*0.15);
            lblIsv.setText(String.valueOf(k));
            lblTtlPgr.setText(String.valueOf(x+k));
        }
    }//GEN-LAST:event_btnIngrArtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrg;
    private javax.swing.JButton btnCncl;
    private javax.swing.JButton btnEncbz;
    private javax.swing.JButton btnGrdr;
    private javax.swing.JButton btnIngrArt;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCantdPrdct;
    private javax.swing.JLabel lblCodPrdct;
    private javax.swing.JLabel lblDescpDet;
    private javax.swing.JLabel lblDescpPrdct;
    private javax.swing.JLabel lblFchEnc;
    private javax.swing.JLabel lblFctEnc;
    private javax.swing.JLabel lblFech;
    private javax.swing.JLabel lblIsv;
    private javax.swing.JLabel lblNoFct;
    private javax.swing.JLabel lblNomb;
    private javax.swing.JLabel lblNombEnc;
    private javax.swing.JLabel lblNombPrdcDetll;
    private javax.swing.JLabel lblNombPrdct;
    private javax.swing.JLabel lblPrVntDet;
    private javax.swing.JLabel lblPrecioPrdct;
    private javax.swing.JLabel lblRtn;
    private javax.swing.JLabel lblRtnEnc;
    private javax.swing.JLabel lblSubTtl;
    private javax.swing.JLabel lblTtlPgr;
    private javax.swing.JPanel pnlAgrgPrdct;
    private javax.swing.JPanel pnlRlzVnt;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTextField txtCantdPrdct;
    private javax.swing.JTextField txtCntdDet;
    private javax.swing.JTextField txtCodPrdct;
    private javax.swing.JTextField txtDescpPrdct;
    private javax.swing.JTextField txtFch;
    private javax.swing.JTextField txtNoFct;
    private javax.swing.JTextField txtNomb;
    private javax.swing.JTextField txtNombPrdct;
    private javax.swing.JTextField txtPreVntPrdct;
    private javax.swing.JTextField txtRtn;
    private javax.swing.JTextField txtbuscarCodigo;
    // End of variables declaration//GEN-END:variables
}
